#!/bin/bash
name="alt"
actions=$1
declare -a sizes=("4" "16" "64" "256" "512" "1024")
runs=15

cd ..
cd c
make
cd ..

for size in "${sizes[@]}"; do
	# Collect CPU cycles and runtime stats
	for run in [0..$runs]; do
		conCount=$(( $size * $actions ))
		# Run C code and save stdout (interactions per second)
		cstats=$cstats+$(./c/test $name $size $actions "1" $conCount)
		# Run Reo code and save stdout (interactions per second)
		tstats=$tstats+$(./treo/test $name $size $actions "1" $conCount)
		#Save those times, or make graph or somethign idk
	done
done

echo $cstats
echo $tstats
